In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunakan untuk komputasi matriks.
Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot.
.....

In [2]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Semarang' 49.0 59000.0]
 ['Solo' 32.0 49000.0]
 ['Jogja' 35.0 57000.0]
 ['Semarang' 43.0 75000.0]
 ['Solo' 45.0 nan]
 ['Jogja' 40.0 70000.0]
 ['Semarang' nan 65000.0]
 ['Solo' 53.0 69000.0]
 ['Jogja' 55.0 78000.0]
 ['Semarang' 42.0 80000.0]]


In [4]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Semarang' 49.0 59000.0]
 ['Solo' 32.0 49000.0]
 ['Jogja' 35.0 57000.0]
 ['Semarang' 43.0 75000.0]
 ['Solo' 45.0 66888.88888888889]
 ['Jogja' 40.0 70000.0]
 ['Semarang' 43.77777777777778 65000.0]
 ['Solo' 53.0 69000.0]
 ['Jogja' 55.0 78000.0]
 ['Semarang' 42.0 80000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encorder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[0.0 1.0 0.0 49.0 59000.0]
 [0.0 0.0 1.0 32.0 49000.0]
 [1.0 0.0 0.0 35.0 57000.0]
 [0.0 1.0 0.0 43.0 75000.0]
 [0.0 0.0 1.0 45.0 66888.88888888889]
 [1.0 0.0 0.0 40.0 70000.0]
 [0.0 1.0 0.0 43.77777777777778 65000.0]
 [0.0 0.0 1.0 53.0 69000.0]
 [1.0 0.0 0.0 55.0 78000.0]
 [0.0 1.0 0.0 42.0 80000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[1 1 0 0 1 0 0 1 0 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [13]:
print(x_train)

[[0.0 1.0 0.0 43.77777777777778 65000.0]
 [0.0 0.0 1.0 45.0 66888.88888888889]
 [0.0 1.0 0.0 49.0 59000.0]
 [0.0 1.0 0.0 43.0 75000.0]
 [0.0 0.0 1.0 32.0 49000.0]
 [0.0 0.0 1.0 53.0 69000.0]
 [1.0 0.0 0.0 55.0 78000.0]
 [1.0 0.0 0.0 40.0 70000.0]]


In [14]:
print(x_test)

[[1.0 0.0 0.0 35.0 57000.0]
 [0.0 1.0 0.0 42.0 80000.0]]


In [15]:
print(y_train)

[0 1 1 0 1 1 0 0]


In [16]:
print(y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 1.0 0.0 -0.19159184384578545 -0.1733583076386543]
 [0.0 0.0 1.0 -0.014117293757057777 0.046984961883374025]
 [0.0 1.0 0.0 0.566708506533324 -0.873272222590979]
 [0.0 1.0 0.0 -0.30453019390224867 0.9931648839485535]
 [0.0 0.0 1.0 -1.9018011447007988 -2.0397954141781867]
 [0.0 0.0 1.0 1.1475343068237058 0.2932509689962288]
 [1.0 0.0 0.0 1.4379472069688968 1.343121841424716]
 [1.0 0.0 0.0 -0.7401495441200351 0.4099032881549496]]


In [19]:
print(x_test)

[[1.0 0.0 0.0 -1.4661817944830124 -1.1065768609084206]
 [0.0 1.0 0.0 -0.44973664397484414 1.5764264797421574]]
